# Splunk Universal Forwarder - inputs.conf
# Configures log sources to forward to Splunk indexer
# Cloud SOC Automation Project

[WinEventLog://Security]
disabled = 0
start_from = oldest
current_only = 0
evt_resolve_ad_obj = 1
checkpointInterval = 5
index = main

[WinEventLog://System]
disabled = 0
start_from = oldest
current_only = 0
index = main

[WinEventLog://Application]
disabled = 0
start_from = oldest
current_only = 0
index = main

[XmlWinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
renderXml = true
index = main
source = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
